# Generated by Django 5.2.4 on 2025-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_payment_initial_khalti_id_payment_khalti_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='initial_khalti_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='khalti_status',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='khalti_transaction_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
