# Generated by Django 5.2.4 on 2025-08-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_admin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='school',
            name='longitude',
        ),
        migrations.AddField(
            model_name='school',
            name='map_location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
