# Generated by Django 5.2.4 on 2025-08-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_tempcsvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Quarterly', 'Quarterly')], default='Yearly', max_length=20),
        ),
    ]
