# Generated by Django 5.2.4 on 2025-08-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_fee_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
