# Generated by Django 5.2.4 on 2025-08-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_grade_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Quarterly', 'Quarterly'), ('Bi Monthly', 'Bi Monthly')], default='Yearly', max_length=20),
        ),
    ]
