# Generated by Django 5.2.4 on 2025-08-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('school_admin', 'School Admin'), ('student', 'Student')], default='school_admin', max_length=20),
        ),
    ]
