# Generated by Django 5.2.4 on 2025-08-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stu_visible_pass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
